### PR TITLE
updated get_component error message from 404 to 422

### PR DESCRIPTION
**Pull request by Tengal-Teemo**
Changed a single number

### CODE REVIEW

**Review by pmeier — DISMISSED** [review]
Thanks!

**Review by pmeier — COMMENTED** [review]
We need to update the corresponding test as well: 

https://github.com/Quansight/ragna/blob/aa2a70263b373baaf40b4c41701c850e40873ad9/tests/deploy/api/test_components.py#L99

**Comment by Tengal-Teemo** [comment]
Sorry @pmeier will fix immediately

**Review by pmeier — APPROVED** [review]
Thanks @Tengal-Teemo!

**Pull request merged**
